### PR TITLE
Fixed a typo in a link

### PR DESCRIPTION
**Pull request by postmodern**
Minor typo fix to the README.

### CODE REVIEW

**Comment by bkuhlmann** [comment]
:bow: Good catch. Actually, I need to add a bunch more documentation that cleans this up further but fixing this is great. 

By the way, would you mind amending your Git commit subject to something like the following?

``` 
Fixed README Rubocop link
```

The reason I ask is because having a [good Git commit message](https://www.alchemists.io/articles/git_commit_anatomy) that explains the *what* is super important for historical reason but also for the release notes generated by [Milestoner](https://www.alchemists.io/projects/milestoner) for this project. It'll also make you look good in the release notes since you're name will be associated. :wink:

**Comment by postmodern** [comment]
Amended.

**Comment by bkuhlmann** [comment]
Thanks! Would you be able to fix the build failure too? Just need a full name for your Git author name.

Apologies for not catching this sooner as I didn't realize Circle CI wasn't building forks of this project until your code review came along.

**Comment by bkuhlmann** [comment]
:information_source: I ended up fixing the above while building the [1.1.0](https://www.alchemists.io/projects/rubysmith/versions) version notes so this is resolved now. Version 1.1.0 includes YARD support as well.

**Pull request closed without merging**
